export const tools = [
  { name: 'Cheat Sheet Generator', path: '/cheat-sheet', description: 'Create and organize custom cheat sheets for quick reference.' },
  { name: 'Habit Tracker', path: '/habit-tracker', description: 'Track and maintain good habits with a visual calendar.' },
  { name: 'Math Practice', path: '/math-practice', description: 'Improve your math skills with customizable practice problems.' },
  { name: 'Grid Layout Builder', path: '/grid-builder', description: 'Design and visualize CSS grid layouts easily.' },
  { name: 'Markdown Converter', path: '/markdown-converter', description: 'Convert Markdown to HTML with live preview.' },
  { name: 'Static Site Generator', path: '/site-generator', description: 'Create simple static websites with Markdown content.' },
  { name: 'Resume Timeline Builder', path: '/resume-builder', description: 'Build an interactive timeline for your resume or CV.' },
  { name: 'Personal Journal', path: '/journal', description: 'Keep a private digital journal with search functionality.' },
  { name: 'Math Equation Visualizer', path: '/equation-visualizer', description: 'Visualize mathematical equations and functions graphically.' },
  { name: 'Pomodoro Timer', path: '/pomodoro', description: 'Boost productivity with a customizable Pomodoro timer.' },
  { name: 'Password Generator', path: '/password-generator', description: 'Generate strong, secure passwords with custom options.' },
  { name: 'Color Palette Generator', path: '/color-palette', description: 'Create harmonious color palettes for your designs.' },
  { name: 'URL Shortener', path: '/url-shortener', description: 'Shorten long URLs for easier sharing and tracking.' },
  { name: 'Regex Tester', path: '/regex-tester', description: 'Test and debug regular expressions with live results.' },
  { name: 'JSON Formatter', path: '/json-formatter', description: 'Format and validate JSON data for improved readability.' },
  { name: 'Code Snippet Manager', path: '/snippet-manager', description: 'Store and organize your frequently used code snippets.' },
  { name: 'Flashcard Study Tool', path: '/flashcards', description: 'Create and study with digital flashcards for effective learning.' },
  { name: 'Mind Map Creator', path: '/mind-map', description: 'Visualize ideas and concepts with interactive mind maps.' },
  { name: 'Expense Tracker', path: '/expense-tracker', description: 'Monitor and categorize your expenses for better financial management.' },
  { name: 'Goal Setting and Tracking', path: '/goal-tracker', description: 'Set, track, and achieve your personal and professional goals.' },
  { name: 'Meditation Timer', path: '/meditation-timer', description: 'Practice mindfulness with a customizable meditation timer.' },
  { name: 'Typing Speed Test', path: '/typing-test', description: 'Measure and improve your typing speed and accuracy.' },
  { name: 'Pixel Art Creator', path: '/pixel-art', description: 'Create pixel art with a simple and intuitive interface.' },
  { name: 'Morse Code Translator', path: '/morse-code', description: 'Translate text to Morse code and vice versa.' },
  { name: 'Unit Converter', path: '/unit-converter', description: 'Convert between various units of measurement.' },
  { name: 'Random Name Generator', path: '/name-generator', description: 'Generate random names for characters, businesses, or projects.' },
  { name: 'Countdown Timer', path: '/countdown', description: 'Create countdown timers for events or deadlines.' },
  { name: 'Dice Roller', path: '/dice-roller', description: 'Roll virtual dice for games or random number generation.' },
  { name: 'Loan Calculator', path: '/loan-calculator', description: 'Calculate loan payments, interest, and amortization schedules.' },
  { name: 'Calorie Counter', path: '/calorie-counter', description: 'Track your daily calorie intake and nutritional information.' },
  { name: 'Sudoku Solver', path: '/sudoku-solver', description: 'Solve Sudoku puzzles with an interactive grid.' },
  { name: 'Crossword Puzzle Generator', path: '/crossword-generator', description: 'Create custom crossword puzzles with your own words and clues.' },
  { name: 'Meme Generator', path: '/meme-generator', description: 'Create custom memes with your own images and text.' },
  { name: 'Kanban Board', path: '/kanban-board', description: 'Organize tasks and projects with a visual Kanban board.' },
  { name: 'Periodic Table Explorer', path: '/periodic-table', description: 'Explore the elements of the periodic table interactively.' },
  { name: 'Astronomy Picture of the Day', path: '/apod', description: 'View and learn about NASA\'s Astronomy Picture of the Day.' },
  { name: 'Inspirational Quote Generator', path: '/quote-generator', description: 'Generate random inspirational quotes to motivate and inspire.' },
  { name: 'Recipe Converter', path: '/recipe-converter', description: 'Convert recipe measurements between different units and serving sizes.' },
  { name: 'Timezone Converter', path: '/timezone-converter', description: 'Convert times between different timezones around the world.' },
  { name: 'Markdown Table Generator', path: '/markdown-table', description: 'Create formatted Markdown tables easily.' },
  { name: 'CSS Flexbox Playground', path: '/flexbox-playground', description: 'Experiment with CSS Flexbox properties in real-time.' },
  { name: 'CSS Grid Playground', path: '/grid-playground', description: 'Explore and learn CSS Grid layout with an interactive tool.' },
  { name: 'SVG Path Editor', path: '/svg-path-editor', description: 'Create and edit SVG paths with a visual interface.' },
  { name: 'Binary/Decimal/Hex Converter', path: '/number-base-converter', description: 'Convert numbers between binary, decimal, and hexadecimal bases.' },
  { name: 'Roman Numeral Converter', path: '/roman-numeral-converter', description: 'Convert between Roman numerals and Arabic numbers.' },
  { name: 'Acronym Generator', path: '/acronym-generator', description: 'Generate acronyms from phrases or sentences.' },
  { name: 'Rhyme Finder', path: '/rhyme-finder', description: 'Find rhyming words for poetry or songwriting.' },
  { name: 'Anagram Solver', path: '/anagram-solver', description: 'Discover anagrams for words or phrases.' },
  { name: 'Word Counter', path: '/word-counter', description: 'Count words, characters, sentences, and paragraphs in your text.' },
  { name: 'Readability Score Calculator', path: '/readability-score', description: 'Calculate the readability score of your text using various metrics.' },
]

